[project]
name = "regenie-workflow"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dxpy>=0.387.0",
    "ipython>=8.31.0",
    "pyyaml>=6.0.2",
    "ruff>=0.8.4",
]
