project: "my UKB project"
priority: "high"
cost_limit: "10"
step1_pvar: ""
step1_pgen: ""
step1_psam: ""
step1_prefix: "ukb_c1-22_GRCh38_full_analysis_set_plus_decoy_hla_merged.qc_pass"
covariates: ""
covariate_string: "sex,age_at_recruitment,gPC1,gPC2,gPC3,gPC4,gPC5,gPC6,gPC7,gPC8,gPC9,gPC10"
categorical_covariate_string: "sex"
phenotypes: ""
final_folder: ""
concatenate: "true"

